char btn_1P[45];
char btn_2P[45];
char btn_Off[45];
char btn_HowTo[45];
char btn_Play[45];
char btn_On[45];
char btn_Options[45];
char btn_Exit[45];
char btn_Back[45];
char btn_Continue[45];
char btn_Defaults[45];
char btn_Fullscreen[45];
char btn_MapOptions[45];
char btn_example[45];

char str_ez[15];
char str_normal[15];
char str_hard[15];
char str_on[15];
char str_off[15];
char str_gndPoints[40];
char str_varBtwPoints[40];
char str_minVarBtwPnts[40];
char str_varBtwMountains[40];
char str_mountainVsize[40];
char str_mountainHsize[40];
char str_mountainChance[40];
char str_resolution[20];
char str_toReshape[80];
char str_pressEnterToContinue[35];
char str_escape[35];
char str_restart[35];
char str_howToPlay0[80];
char str_howToPlay1[80];
char str_howToPlay2[80];
char str_howToPlay3[80];
char str_howToPlay4[80];
char str_howToPlay5[80];
char str_howToPlay6[80];
char str_howToPlay7[80];
char str_howToPlay8[80];
char str_howToPlay9[80];
char str_howToPlay10[80];
char str_howToPlay11[80];
char str_howToPlay12[80];
char str_howToPlay13[80];
char str_music[20];
char str_pause[20];
char str_sound[20];
char str_Language[20];
char str_wind[20];
char str_mapgen[20];
char str_difficulty[20];
char str_lifeInitAmount[35];
char str_bombInitAmount[50];
char str_RussiaWon[25];
char str_BRWon[25];
char str_USAWon[25];
char str_IslamicWon[30];
char str_KoreaWon[30];
char str_Lifes[20];
char str_Projetile[15];
char str_AtomicBombs[25];
char str_Strength[20];
char str_Angle[20];
char str_CheatOn[20];
char str_currentMap[30];


void setStrings(){
  if(strEq(language,"portugues")){
      strcpy(btn_1P,"GUIandHUD/Buttons/pt/woglow/1Jogador.png");
      strcpy(btn_2P,"GUIandHUD/Buttons/pt/woglow/2Jogadores.png");
      strcpy(btn_Off,"GUIandHUD/Buttons/pt/woglow/Desligado.png");
      strcpy(btn_HowTo,"GUIandHUD/Buttons/pt/woglow/Instrucoes.png");
      strcpy(btn_Play,"GUIandHUD/Buttons/pt/woglow/Jogar.png");
      strcpy(btn_On,"GUIandHUD/Buttons/pt/woglow/Ligado.png");
      strcpy(btn_Options,"GUIandHUD/Buttons/pt/woglow/Opcoes.png");
      strcpy(btn_Exit,"GUIandHUD/Buttons/pt/woglow/Sair.png");
      strcpy(btn_Back,"GUIandHUD/Buttons/pt/woglow/Voltar.png");
      strcpy(btn_Continue,"GUIandHUD/Buttons/pt/woglow/Continuar.png");
      strcpy(btn_Fullscreen,"GUIandHUD/Buttons/en/woglow/fulsscreen.png");
      strcpy(btn_Defaults,"GUIandHUD/Buttons/pt/woglow/padroes.png");
      strcpy(btn_MapOptions,"GUIandHUD/Buttons/pt/woglow/mapopt.png");
      strcpy(btn_example,"GUIandHUD/Buttons/pt/woglow/sample.png");
      strcpy(str_pressEnterToContinue,"Pressione ENTER para iniciar");
      strcpy(str_howToPlay0,"Instrucoes de jogo:");
      strcpy(str_howToPlay1,"	-O objetivo do jogo é vencer a guerra nuclear contra ");
      strcpy(str_howToPlay2,"	  todos os paises,para se afirmar como superpotencia,");
      strcpy(str_howToPlay3,"	  ou apenas para destruir a vida na terra,voce escolhe!!!");
      strcpy(str_howToPlay4,"	-No turno de cada jogador,ele pode andar e atirar,");
      strcpy(str_howToPlay5,"	  com o objetivo de acertar e matar o lider do pais ");
      strcpy(str_howToPlay6,"	  inimigo,os comandos para jogar são:");
      strcpy(str_howToPlay7,"	-[WASD] para se locomover e pular");
      strcpy(str_howToPlay8,"	-[T] para alternar entre misses e bombas atomicas");
      strcpy(str_howToPlay9,"		(ATENCAO:o estoque de bombas atomicas e limitado)");
      strcpy(str_howToPlay10,"  -[P] para pausar");
      strcpy(str_howToPlay11,"  -[R] para reiniciar o jogo");
      strcpy(str_howToPlay12,"	-Use o mouse para mirar e botao esquerdo para atirar");
      strcpy(str_howToPlay13,"	-Segure o botao do mouse para ajustar a forca do tiro");
      strcpy(str_music,"Musica:");
      strcpy(str_wind,"Vento:");
      strcpy(str_mapgen,"Geracao de mapa:");
      strcpy(str_difficulty,"Dificuldade:");
      strcpy(str_lifeInitAmount,"Quantidade inicial de vidas:");
      strcpy(str_bombInitAmount,"Quantidade inicial de bombas atomicas:");
      strcpy(str_sound,"Som:");
      strcpy(str_Language,"Idioma:");
      strcpy(str_pause,"Pausado");
      strcpy(str_RussiaWon,"Vitoria da Russia!");
      strcpy(str_BRWon,"Vitoria do Brasil!");
      strcpy(str_USAWon,"Vitoria dos EUA!");
      strcpy(str_IslamicWon,"Allahu Akbar!!!");
      strcpy(str_KoreaWon,"Vitoria da Coreia do Norte!");
      strcpy(str_Lifes,"Vidas:");
      strcpy(str_Projetile,"Projetil:");
      strcpy(str_AtomicBombs,"Bombas Atomicas:");
      strcpy(str_Strength,"Forca:");
      strcpy(str_Angle,"Angulo:");
      strcpy(str_CheatOn,"Trapaca Ligada");
      strcpy(str_escape,"Deseja sair?");
      strcpy(str_restart,"Deseja reiniciar?");
      strcpy(str_resolution,"Resolucao:");
      strcpy(str_toReshape,"Para redimencionar a tela,va ao menu de opcoes");
      strcpy(str_gndPoints,"Numero de pontos:");
      strcpy(str_varBtwPoints,"Variacao entre pontos:");
      strcpy(str_minVarBtwPnts,"Variacao minima entre pontos:");
      strcpy(str_varBtwMountains,"Variacao entre Vales/Montanhas:");
      strcpy(str_mountainVsize,"Tamanho vertical de Vales/Montanhas:");
      strcpy(str_mountainHsize,"Tamanho horizontal de Vales/Montanhas:");
      strcpy(str_mountainChance,"Chance de Vale/Montanha:");
      strcpy(str_on,"Ligado");
      strcpy(str_off,"Desligado");
      strcpy(str_ez,"Facil");
      strcpy(str_normal,"Normal");
      strcpy(str_hard,"Dificil <3");
      strcpy(str_currentMap,"Mapa Atual:");
  }else if(strEq(language,"english")){
      strcpy(btn_1P,"GUIandHUD/Buttons/en/woglow/1Player.png");
      strcpy(btn_2P,"GUIandHUD/Buttons/en/woglow/2Players.png");
      strcpy(btn_Off,"GUIandHUD/Buttons/en/woglow/Off.png");
      strcpy(btn_HowTo,"GUIandHUD/Buttons/en/woglow/Instructions.png");
      strcpy(btn_Play,"GUIandHUD/Buttons/en/woglow/Play.png");
      strcpy(btn_On,"GUIandHUD/Buttons/en/woglow/On.png");
      strcpy(btn_Options,"GUIandHUD/Buttons/en/woglow/Options.png");
      strcpy(btn_Exit,"GUIandHUD/Buttons/en/woglow/Exit.png");
      strcpy(btn_Back,"GUIandHUD/Buttons/en/woglow/Back.png");
      strcpy(btn_Continue,"GUIandHUD/Buttons/en/woglow/continue.png");
      strcpy(btn_Fullscreen,"GUIandHUD/Buttons/en/woglow/fulsscreen.png");
      strcpy(btn_Defaults,"GUIandHUD/Buttons/en/woglow/defaults.png");
      strcpy(btn_MapOptions,"GUIandHUD/Buttons/en/woglow/mapOptions.png");
      strcpy(btn_example,"GUIandHUD/Buttons/en/woglow/sample.png");
      strcpy(str_pressEnterToContinue,"Press ENTER to continue");
      strcpy(str_howToPlay0,"Game Instructions:");
      strcpy(str_howToPlay1,"	-The game's goal is to win the nuclear war against");
      strcpy(str_howToPlay2,"	  every country,to ensure yourself as a superpower,");
      strcpy(str_howToPlay3,"		or just to destroy all life in Earth,you pick!!!");
      strcpy(str_howToPlay4,"	-In each player's turn,it can walk and shoot,");
      strcpy(str_howToPlay5,"	  to hit and kill the enemy country's leader,");
      strcpy(str_howToPlay6,"	  the key mapping is:");
      strcpy(str_howToPlay7,"	-[WASD] to walk and jump");
      strcpy(str_howToPlay8,"	-[T] to change between missiles and atomic bombs");
      strcpy(str_howToPlay9,"		(CAUTION:the ammount of atomic bombs is limited)");
      strcpy(str_howToPlay10,"	-[P] to pause");
      strcpy(str_howToPlay11,"	-[R] to restart the game");
      strcpy(str_howToPlay12,"	-Use the mouse to aim and the left button to shoot");
      strcpy(str_howToPlay13,"	-Hold the mouse button to adjust the shot's strenght");
      strcpy(str_music,"Music:");
      strcpy(str_wind,"Wind:");
      strcpy(str_mapgen,"Map gen:");
      strcpy(str_difficulty,"Difficulty:");
      strcpy(str_lifeInitAmount,"Initial amount of lives:");
      strcpy(str_bombInitAmount,"Initial amount of atomic bombs:");
      strcpy(str_sound,"Sound:");
      strcpy(str_Language,"Language:");
      strcpy(str_pause,"Paused");
      strcpy(str_RussiaWon,"Russia Wins!");
      strcpy(str_BRWon,"Brazil Wins!");
      strcpy(str_USAWon,"USA Wins!");
      strcpy(str_IslamicWon,"Allahu Akbar!!!");
      strcpy(str_KoreaWon,"North Korea Wins!");
      strcpy(str_Lifes,"Lives:");
      strcpy(str_Projetile,"Projectile:");
      strcpy(str_AtomicBombs,"Atomic Bombs:");
      strcpy(str_Strength,"Strength:");
      strcpy(str_Angle,"Angle:");
      strcpy(str_CheatOn,"CHEAT ON");
      strcpy(str_escape,"Wanna leave?");
      strcpy(str_restart,"Gonna cry?");
      strcpy(str_resolution,"Resolution:");
      strcpy(str_toReshape,"To reshape the window,go to options menu");
      strcpy(str_gndPoints,"Number of Ground Points:");
      strcpy(str_varBtwPoints,"Variation between points:");
      strcpy(str_minVarBtwPnts,"Minimum variation between points:");
      strcpy(str_varBtwMountains,"Variation between Mountain/Pit points:");
      strcpy(str_mountainVsize,"Mountain/Pit Vertical size:");
      strcpy(str_mountainHsize,"Mountain/Pit Horizontal size:");
      strcpy(str_mountainChance,"Mountain/Pit Chance:");
      strcpy(str_on,"On");
      strcpy(str_off,"Off");
      strcpy(str_ez,"Easy");
      strcpy(str_normal,"Normal");
      strcpy(str_hard,"HARD");
      strcpy(str_currentMap,"Current Map:");
  }else if(strEq(language,"russkiy")){//russo
    strcpy(btn_1P,"GUIandHUD/Buttons/ru/woglow/1jogador.png");
    strcpy(btn_2P,"GUIandHUD/Buttons/ru/woglow/2jogadores.png");
    strcpy(btn_Off,"GUIandHUD/Buttons/ru/woglow/desligado.png");
    strcpy(btn_HowTo,"GUIandHUD/Buttons/ru/woglow/instrucoes.png");
    strcpy(btn_Play,"GUIandHUD/Buttons/ru/woglow/jogar.png");
    strcpy(btn_On,"GUIandHUD/Buttons/ru/woglow/ligado.png");
    strcpy(btn_Options,"GUIandHUD/Buttons/ru/woglow/opcoes.png");
    strcpy(btn_Exit,"GUIandHUD/Buttons/ru/woglow/sair.png");
    strcpy(btn_Back,"GUIandHUD/Buttons/ru/woglow/voltar.png");
    strcpy(btn_Continue,"GUIandHUD/Buttons/ru/woglow/continuar.png");
    strcpy(btn_Fullscreen,"GUIandHUD/Buttons/ru/woglow/fulsscreen.png");
    strcpy(btn_Defaults,"GUIandHUD/Buttons/ru/woglow/defaultsRusso.png");
    strcpy(btn_MapOptions,"GUIandHUD/Buttons/ru/woglow/mapoptionsRusso.png");
    strcpy(btn_example,"GUIandHUD/Buttons/ru/woglow/exemploRusso.png");
    strcpy(str_pressEnterToContinue,"Nazhmite knopku ENTER, chtoby nachat'");
    strcpy(str_howToPlay0,"Igra Instruktsii :");
    strcpy(str_howToPlay1,"  -Tsel' igra yavlyayetsya , chtoby vyigrat' voynu protiv yadernoy");
    strcpy(str_howToPlay2,"   kazhdaya strana , chtoby obespechit' sebya kak sverkhderzhava ,");
    strcpy(str_howToPlay3,"   ili prosto unichtozhit' vsyu zhizn' na zemle, vy vybirayete !!!");
    strcpy(str_howToPlay4,"	-V Khoda kazhdogo igroka , on mozhet khodit' i strelyat',");
    strcpy(str_howToPlay5,"	  udarit' i ubit' lidera vrazheskoy strany ,");
    strcpy(str_howToPlay6,"	  klyuch otobrazheniye :");
    strcpy(str_howToPlay7,"	-[WASD] , chtoby khodit' i prygat'");
    strcpy(str_howToPlay8,"	-[T] dlya pereklyucheniya mezhdu raketami i atomnymi bombami");
    strcpy(str_howToPlay9,"		(VNIMANIYE: summoy atomnykh bomb ogranicheno )");
    strcpy(str_howToPlay10,"	-[P], chtoby priostanovit'");
    strcpy(str_howToPlay11,"	-[R], chtoby perezapustit' igru");
    strcpy(str_howToPlay12,"	-Ispol'zuyte Mysh', chtoby pritselit'sya i levuyu knopku myshi , chtoby strelyat'");
    strcpy(str_howToPlay13,"	-Postoy Knopku myshi dlya regulirovki strenght vystrela v");
    strcpy(str_music,"Muzyka:");
    strcpy(str_wind,"veter:");
    strcpy(str_mapgen,"Generatsiya karty:");
    strcpy(str_difficulty,"Uroven' slozhnosti:");
    strcpy(str_lifeInitAmount,"Nachal'noye kolichestvo zhizney:");
    strcpy(str_bombInitAmount,"nachal'noye kolichestvo atomnykh bomb:");
    strcpy(str_sound,"zvuk:");
    strcpy(str_Language,"yazyk:");
    strcpy(str_pause,"priostanovlena");
    strcpy(str_RussiaWon,"Pobeda Rossii!");
    strcpy(str_BRWon,"Pobeda Brazilii");
    strcpy(str_USAWon,"Pobeda SSHA!");
    strcpy(str_IslamicWon,"Allahu Akbar!!!");
    strcpy(str_KoreaWon,"Pobeda Severnaya Koreya!");
    strcpy(str_Lifes,"zhivet:");
    strcpy(str_Projetile,"snaryad:");
    strcpy(str_AtomicBombs,"Atomnyye bomby:");
    strcpy(str_Strength,"sila:");
    strcpy(str_Angle,"Ugol:");
    strcpy(str_CheatOn,"obmanyval");
    strcpy(str_escape,"Vy khotite ostavit'?");
    strcpy(str_restart,"Vy khotite perezapustit'?");
    strcpy(str_resolution,"razresheniye:");
    strcpy(str_toReshape,"Chtoby izmenit' formu okna, pereydite v menyu optsiy");
    strcpy(str_gndPoints,"Kolichestvo opornykh tochek:");
    strcpy(str_varBtwPoints,"Raskhozhdeniye mezhdu tochki:");
    strcpy(str_minVarBtwPnts,"Minimal'naya raznitsa mezhdu tochki:");
    strcpy(str_varBtwMountains,"Raskhozhdeniye mezhdu Gora/yama tochki:");
    strcpy(str_mountainVsize,"Gora/yama vertikal'nyy razmer:");
    strcpy(str_mountainHsize,"Gora/yama gorizontal'nyy razmer:");
    strcpy(str_mountainChance,"Gora/yama shans:");
    strcpy(str_on,"soyedinennyy");
    strcpy(str_off,"ot");
    strcpy(str_ez,"legko");
    strcpy(str_normal,"normal'nyy");
    strcpy(str_hard,"trudno");
    strcpy(str_currentMap,"tekushchaya karta:");
  }else if(strEq(language,"hangug-ui")){//coreano fonetico
    strcpy(btn_1P,"GUIandHUD/Buttons/ko/woglow/1jogador.png");
    strcpy(btn_2P,"GUIandHUD/Buttons/ko/woglow/2jogadores.png");
    strcpy(btn_Off,"GUIandHUD/Buttons/ko/woglow/desligado.png");
    strcpy(btn_HowTo,"GUIandHUD/Buttons/ko/woglow/instrucoes.png");
    strcpy(btn_Play,"GUIandHUD/Buttons/ko/woglow/jogar.png");
    strcpy(btn_On,"GUIandHUD/Buttons/ko/woglow/ligado.png");
    strcpy(btn_Options,"GUIandHUD/Buttons/ko/woglow/opcoes.png");
    strcpy(btn_Exit,"GUIandHUD/Buttons/ko/woglow/sair.png");
    strcpy(btn_Back,"GUIandHUD/Buttons/ko/woglow/voltar.png");
    strcpy(btn_Continue,"GUIandHUD/Buttons/ko/woglow/continuar.png");
    strcpy(btn_Fullscreen,"GUIandHUD/Buttons/ko/woglow/fulsscreen.png");
    strcpy(btn_Defaults,"GUIandHUD/Buttons/ko/woglow/defaultsCoreano.png");
    strcpy(btn_MapOptions,"GUIandHUD/Buttons/ko/woglow/mapoptionsCoreano.png");
    strcpy(btn_example,"GUIandHUD/Buttons/ko/woglow/sample.png");
    strcpy(str_pressEnterToContinue,"leul nulleo sijaghabnida");
    strcpy(str_howToPlay0,"geim bangbeob :");
    strcpy(str_howToPlay1," -nyeon geim ui mogpyo e daehae haeg jeonjaeng-eul seungli haneun geos-ibnida");
    strcpy(str_howToPlay2,"   modeun gugga neun chogangdaegug eulo jasin-eul bojanghagi wihae animyeon ");
    strcpy(str_howToPlay3,"   geunyang jigu eissneun modeun saengmyeong-eul pagoehaneun , dangsin-eun seontaeg !");
    strcpy(str_howToPlay4,"	-gag peulleieoui teon -in , geugeos-eun dobolo chwal-yeonghal su issseubnida ,");
    strcpy(str_howToPlay5,"	  gong-gyeog gwa jeog-ui guggaui jidojaleul jug-il ,");
    strcpy(str_howToPlay6,"	  ki maeping eun da-eumgwa gatseubnida");
    strcpy(str_howToPlay7,"	-[WASD] neun dobolo idonghabnida");
    strcpy(str_howToPlay8,"	-[T] neun misailgwa wonja pogtan saie byeongyeong");
    strcpy(str_howToPlay9,"   ( JUUI : wonja pogtan ui aegsu ga jehandoebnida )");
    strcpy(str_howToPlay10,"  -[P] leul ilsi jungji");
    strcpy(str_howToPlay11,"	-[R] eun geim-eul dasi sijaghabnida");
    strcpy(str_howToPlay12,"	-chwal-yeong-eul mogpyolo mauseu oenjjog beoteun-eul -use");
    strcpy(str_howToPlay13,"	-syas ui strenght eul jojeong mauseu beoteun-eul kkwag jab-ala");
    strcpy(str_music,"eum-ag:");
    strcpy(str_wind,"balam:");
    strcpy(str_mapgen,"maeb saengseong:");
    strcpy(str_difficulty,"nan-ido:");
    strcpy(str_lifeInitAmount,"salm ui chogi lyang:");
    strcpy(str_bombInitAmount,"wonja pogtan ui chogi lyang:");
    strcpy(str_sound,"soli:");
    strcpy(str_Language,"eon-eo:");
    strcpy(str_pause,"ilsi jungji");
    strcpy(str_RussiaWon,"leosia eseo seungli!");
    strcpy(str_BRWon,"beulajil eseo seungli!");
    strcpy(str_USAWon,"migug-ui seungli!");
    strcpy(str_IslamicWon,"Allahu Akbar!!!");
    strcpy(str_KoreaWon,"bughan ui seungli!");
    strcpy(str_Lifes,"salm:");
    strcpy(str_Projetile,"balsa mul:");
    strcpy(str_AtomicBombs,"wonja pogtan:");
    strcpy(str_Strength,"him:");
    strcpy(str_Angle,"gagdo:");
    strcpy(str_CheatOn,"e bujeong haeng-wi");
    strcpy(str_escape,"dangsin-eun tteonago sip-eo?");
    strcpy(str_restart,"dangsin-eun dasi sijag hago sip-eo?");
    strcpy(str_resolution,"haegyeol:");
    strcpy(str_toReshape,"chang moyang-eul byeongyeong halyeomyeon obsyeon menyulo idong");
    strcpy(str_gndPoints,"jeobji pointeu ui su:");
    strcpy(str_varBtwPoints,"jeom saiui byeonhwa:");
    strcpy(str_minVarBtwPnts,"jeom saiui choeso byeonhwa:");
    strcpy(str_varBtwMountains,"san/piteu jijeom saiui byeonhwa:");
    strcpy(str_mountainVsize,"san/piteu selo keugi:");
    strcpy(str_mountainHsize,"san/piteu galo keugi:");
    strcpy(str_mountainChance,"san/piteu/Pit gihoe:");
    strcpy(str_on,"yeongyeol");
    strcpy(str_off,"tteol-eojyeoseo");
    strcpy(str_ez,"swibge");
    strcpy(str_normal,"pyojun");
    strcpy(str_hard,"eolyeoun");
    strcpy(str_currentMap,"hyeonjaejido:");
  }else{//arabe
    strcpy(btn_1P,"GUIandHUD/Buttons/ar/woglow/1jogador.png");
    strcpy(btn_2P,"GUIandHUD/Buttons/ar/woglow/2jogadores.png");
    strcpy(btn_Off,"GUIandHUD/Buttons/ar/woglow/desligado.png");
    strcpy(btn_HowTo,"GUIandHUD/Buttons/ar/woglow/instrucoes.png");
    strcpy(btn_Play,"GUIandHUD/Buttons/ar/woglow/jogar.png");
    strcpy(btn_On,"GUIandHUD/Buttons/ar/woglow/ligado.png");
    strcpy(btn_Options,"GUIandHUD/Buttons/ar/woglow/opcoes.png");
    strcpy(btn_Exit,"GUIandHUD/Buttons/ar/woglow/sair.png");
    strcpy(btn_Back,"GUIandHUD/Buttons/ar/woglow/voltar.png");
    strcpy(btn_Continue,"GUIandHUD/Buttons/ar/woglow/continuar.png");
    strcpy(btn_Fullscreen,"GUIandHUD/Buttons/ar/woglow/fulsscreen.png");
    strcpy(btn_Defaults,"GUIandHUD/Buttons/ar/woglow/defaultsArabe.png");
    strcpy(btn_MapOptions,"GUIandHUD/Buttons/ar/woglow/mapoptionsArabe.png");
    strcpy(btn_example,"GUIandHUD/Buttons/ar/woglow/exampleArabe.png");
    strcpy(str_pressEnterToContinue,"adght ENTER libad");
    strcpy(str_howToPlay0,"taelimat alllaebata:");
    strcpy(str_howToPlay1," -alhadaf -The allluebat hu alfawz fi harb nawawiat didd");
    strcpy(str_howToPlay2,"   kl balad , lidaman nafsak kaquwwat euzmaa ،");
    strcpy(str_howToPlay3,"   'aw limujrud tadmir jmye 'ashkal alhayat fi al'ard , yumkinuk aikhtiar !!!");
    strcpy(str_howToPlay4,"	-fy bidawrih kl laeib , ymkn 'an tamshi ​​watlaq alnnari,");
    strcpy(str_howToPlay5,"	  lidarb w qutil zaeim albilad aleaduww ،");
    strcpy(str_howToPlay6,"	  taeyin alrrayiysi hu :");
    strcpy(str_howToPlay7,"	-[WASD] ealaa almashi walqafz");
    strcpy(str_howToPlay8,"	-[T] litaghyir bayn alssawarikh walqanabil aldhdhrria");
    strcpy(str_howToPlay9,"   (TUNBIH : yaqtasir ammount alqanabil aldhdhrria )");
    strcpy(str_howToPlay10,"  -[P] 'iilaa waqfa");
    strcpy(str_howToPlay11,"	-[R] li'iieadat tashghil alllueba");
    strcpy(str_howToPlay12,"	-aistikhdam almawis lihadaf w alzzrr al'aysar li'iitlaq alnnar");
    strcpy(str_howToPlay13,"	-Hold ealaa zirr almawis l dabt satarinat alnnar fi");
    strcpy(str_music,"almusiqaa:");
    strcpy(str_wind,"alrriah:");
    strcpy(str_mapgen,"khritat jyl:");
    strcpy(str_difficulty,"alseubat:");
    strcpy(str_lifeInitAmount,"almablagh al'awwali min hayat:");
    strcpy(str_bombInitAmount,"almablagh al'awwali min alqanabil aldhdharit:");
    strcpy(str_sound,"sut:");
    strcpy(str_Language,"lghat:");
    strcpy(str_pause,"twaqaf");
    strcpy(str_RussiaWon,"aintisar rwsya!");
    strcpy(str_BRWon,"fuz albarazil!");
    strcpy(str_USAWon,"fwaz alwilayat almuttahidat!");
    strcpy(str_IslamicWon,"alllah 'akbr!!!"); ///الله أكبر!!!
    strcpy(str_KoreaWon,"fwaz kuria alshmaly!");
    strcpy(str_Lifes,"yeish:");
    strcpy(str_Projetile,"qdhifat:");
    strcpy(str_AtomicBombs,"qnabul dharit:");
    strcpy(str_Strength,"qut:");
    strcpy(str_Angle,"anjulu:");
    strcpy(str_CheatOn,"alghsh fy");
    strcpy(str_escape,"kunt 'urid 'an 'atruk?");
    strcpy(str_restart,"hal turid 'iieadat tashghil?");
    strcpy(str_resolution,"qarar:");
    strcpy(str_toReshape,"li'iieadat tashkil al'iitar, aintaqil 'iilaa qayimat alkhiarat");
    strcpy(str_gndPoints,"eadad niqat al'ardi:");
    strcpy(str_varBtwPoints,"alaikhtilaf bayn niqat:");
    strcpy(str_minVarBtwPnts,"tabayun alhadd al'adnaa bayn niqat:");
    strcpy(str_varBtwMountains,"alaikhtilaf bayn niqat aljabal/hufra:");
    strcpy(str_mountainVsize,"aljabal/hufra hajm aleumudi:");
    strcpy(str_mountainHsize,"aljabal/hufra hajm al'afaqi:");
    strcpy(str_mountainChance,"aljabal/hufra fursa:");
    strcpy(str_on,"muttasil");
    strcpy(str_off,"baeidanaan");
    strcpy(str_ez,"sahl");
    strcpy(str_normal,"tabiei");
    strcpy(str_hard,"saeb");
    strcpy(str_currentMap,"kharitat alhalia:");
  }
}
